rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
- pattern: main
  isAdminEnforced: true
  requiredStatusCheckContexts:
    - 'lint'
    - 'test (10)'
    - 'test (12)'
    - 'test (14)'
    - 'test (16)'
    - 'cla/google'
    - 'windows'
    - 'OwlBot Post Processor'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
permissionRules:
  - team: Googlers
    permission: pull
  - team: github-automation
    permission: push
  - team: yoshi-admins
    permission: admin
